# Generated by Django 3.2.7 on 2021-10-15 15:57

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datenav', models.DateField()),
                ('heurenav', models.TimeField()),
                ('dureenav', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=60)),
                ('firstname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=60)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=60)),
                ('firstname', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=60)),
                ('firstname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=60)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openlake_core.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latgps', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('longgps', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=8)),
                ('ph', models.DecimalField(decimal_places=4, max_digits=8)),
                ('conductivity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('freqbat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openlake_core.analysis')),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openlake_core.drone'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='lake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openlake_core.lake'),
        ),
    ]
