# Generated by Django 3.2.7 on 2021-10-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openlake_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='latgps',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
