# Generated by Django 3.2.7 on 2021-10-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openlake_core', '0003_remove_data_latgps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='freqbat',
        ),
        migrations.RemoveField(
            model_name='data',
            name='longgps',
        ),
    ]
