# Generated by Django 3.2.7 on 2021-10-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openlake_core', '0004_auto_20211017_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='dureenav',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='heurenav',
        ),
    ]
