# Generated by Django 3.2.7 on 2021-10-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openlake_core', '0005_auto_20211021_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='freqbat',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='latgps',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='longgps',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='conductivity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
