# Generated by Django 3.2.7 on 2021-11-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openlake_core', '0006_auto_20211022_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='avg_conduc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='avg_ph',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='avg_temp',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='durationnav',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='hournav',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
