# Generated by Django 3.2.7 on 2021-11-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openlake_core', '0007_auto_20211118_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='durationnav',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='lake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openlake_core.lake'),
        ),
        migrations.AlterField(
            model_name='data',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openlake_core.analysis'),
        ),
    ]
