# Generated by Django 3.2.7 on 2021-12-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openlake_core', '0008_auto_20211119_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='avg_oxygen',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='depht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='oxygen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
