# Generated by Django 3.2.7 on 2021-12-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openlake_core', '0009_auto_20211210_0841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pilot',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='contributor',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
