version: '3.8'

services:
  web:
    build: 
      context: ./backend/
      dockerfile: ./docker/Dockerfile-django
    image: gitlab.ensimag.fr:5050/monsemps/open-lake-health/openlake-django
    command: /home/django/venv/bin/gunicorn OpenLakeAPIs.wsgi:application --bind 0.0.0.0:80
    volumes:
      - static_volume:/home/django/OpenLakeAPIs/staticfiles
    #   - ./backend/OpenLakeAPIs/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./backend/docker/docker_django-prod.env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=openlake
      - POSTGRES_PASSWORD=openlake
      - POSTGRES_DB=openlake
  

  nginx:
    # image: nginx:1.20.1
    build: 
      context: ./frontend/
      dockerfile: ./docker/nginx/Dockerfile-nginx
    image: gitlab.ensimag.fr:5050/monsemps/open-lake-health/openlake-nginx
    ports:
      - 80:80
    volumes:
      # - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/web/staticfiles
      # - ./frontend/OpenLakeWEB/dist/OpenLakeWEB/:/home/app/web/frontend
      #2
      - ./frontend/docker/nginx/openlake.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/docker/nginx/modsecurity.conf:/etc/nginx/modsec/modsecurity.conf
      - ./frontend/docker/nginx/main.conf:/etc/nginx/modsec/main.conf
      - ./frontend/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: