version: '3.8'

services:
  web:
    build: 
      context: ./backend/
      dockerfile: ./docker/Dockerfile-django
    image: openlake-django
    command: /home/django/venv/bin/python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/django/OpenLakeAPIs/staticfiles
      # - ./backend/OpenLakeAPIs/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/docker/docker_django-dev.env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=openlake
      - POSTGRES_PASSWORD=openlake
      - POSTGRES_DB=openlake
  

  angular:
    build: 
      context: ./frontend/
      dockerfile: ./docker/angular/Dockerfile-angular
    image: openlake-angular
    ports:
      - 4200:4200
    volumes:
      - ./frontend/OpenLakeWEB/:/app/code/
    #   - static_volume:/home/app/web/staticfiles
    #   - ./frontend/OpenLakeWEB/dist/OpenLakeWEB/:/home/app/web/frontend
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
