# base image
FROM nginx:1.18.0
#change version

#https://www.nginx.com/blog/compiling-and-installing-modsecurity-for-open-source-nginx/

#2 – Install Prerequisite Packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-utils autoconf automake build-essential git libcurl4-openssl-dev libgeoip-dev liblmdb-dev libpcre++-dev libtool libxml2-dev libyajl-dev pkgconf wget zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

#3 – Download and Compile the ModSecurity 3.0 Source Code
RUN git clone --depth 1 -b v3/master --single-branch https://github.com/SpiderLabs/ModSecurity \
    && cd ModSecurity \
    && git submodule init \
    && git submodule update \
    && ./build.sh \
    && ./configure \
    && make \
    && make install \
    && cd .. 

#4 – Download the NGINX Connector for ModSecurity and Compile It as a Dynamic Module
RUN git clone --depth 1 https://github.com/SpiderLabs/ModSecurity-nginx.git \
    && nginx -v \
    && wget http://nginx.org/download/nginx-1.18.0.tar.gz \
    && tar zxvf nginx-1.18.0.tar.gz \
    && cd nginx-1.18.0 \
    && ./configure --with-compat --add-dynamic-module=../ModSecurity-nginx \
    && make modules \
    && cp objs/ngx_http_modsecurity_module.so /etc/nginx/modules \
    # && cp objs/ngx_http_modsecurity_module.so /usr/share/nginx/modules/ngx_http_modsecurity_module.so \
    && cd ..

RUN cd nginx-1.18.0 \
    && ls -l /usr/share/nginx/


RUN mkdir /etc/nginx/modsec \
    # && wget -P /etc/nginx/modsec/ https://raw.githubusercontent.com/SpiderLabs/ModSecurity/v3/master/modsecurity.conf-recommended \
    # && mv /etc/nginx/modsec/modsecurity.conf-recommended /etc/nginx/modsec/modsecurity.conf \
    && cp ModSecurity/unicode.mapping /etc/nginx/modsec 
    # && sed -i 's/SecRuleEngine DetectionOnly/SecRuleEngine On/' /etc/nginx/modsec/modsecurity.conf 

# RUN echo 'Include "/etc/nginx/modsec/modsecurity.conf"' > /etc/nginx/modsec/main.conf
# RUN echo 'SecRule ARGS:testparam "@contains test" "id:1234,deny,status:403"' >> /etc/nginx/modsec/main.conf


COPY ./OpenLakeWEB/dist/OpenLakeWEB/ /home/app/web/frontend