# base image
FROM node:14.18.0 
#change version


# install chrome for protractor tests
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
WORKDIR /app/

# install and cache app dependencies
COPY ./OpenLakeWEB/package.json /app/package.json
RUN npm install 
RUN /app/node_modules/.bin/npm install --save-dev @angular-devkit/build-angular

# set working directory
WORKDIR /app/code/

# start app
CMD /app/node_modules/.bin/ng serve --host 0.0.0.0
